#!/bin/bash
# Script per catturare screenshot dell'app StepsTracker

# Colori per output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}📱 StepsTracker - Screenshot Guide${NC}"
echo ""

# Verifica che adb sia disponibile
if ! command -v adb &> /dev/null; then
    echo "❌ adb non trovato! Installa Android SDK."
    exit 1
fi

# Trova il path dell'APK
APK_PATH="android/app/build/outputs/apk/debug/app-debug.apk"
if [ ! -f "$APK_PATH" ]; then
    echo "❌ APK non trovato! Esegui prima: just android-build"
    exit 1
fi

echo -e "${GREEN}✅ APK trovato: $APK_PATH${NC}"
echo ""

echo "📋 ISTRUZIONI PER GLI SCREENSHOT:"
echo "================================"
echo ""
echo "1️⃣  AVVIA L'EMULATORE:"
echo "   - Apri Android Studio"
echo "   - Tools → AVD Manager"
echo "   - Crea/Avvia un emulatore Android 14+"
echo ""
echo "2️⃣  INSTALLA L'APP (quando l'emulatore è pronto):"
echo "   adb install -r $APK_PATH"
echo ""
echo "3️⃣  LOGIN CON ACCOUNT DEMO:"
echo "   Email: demo@example.com"
echo "   Password: demo"
echo ""
echo "4️⃣  CATTURA GLI SCREENSHOT:"
echo ""
echo "   a) HOME SCREEN (home.png):"
echo "      - Dashboard con conteggio passi del giorno"
echo "      - Grafico dei trend settimanali"
echo "      adb shell screencap -p /sdcard/home.png"
echo "      adb pull /sdcard/home.png docs/screenshots/"
echo ""
echo "   b) STATISTICHE (statistics.png):"
echo "      - Tocca l'icona del grafico"
echo "      - Mostra distribuzione oraria"
echo "      adb shell screencap -p /sdcard/statistics.png"
echo "      adb pull /sdcard/statistics.png docs/screenshots/"
echo ""
echo "   c) PROFILO (profile.png):"
echo "      - Tocca l'icona del profilo"
echo "      - Mostra dati fisici dell'utente"
echo "      adb shell screencap -p /sdcard/profile.png"
echo "      adb pull /sdcard/profile.png docs/screenshots/"
echo ""
echo "   d) IMPOSTAZIONI (settings.png):"
echo "      - Menu → Impostazioni"
echo "      - Mostra configurazione server"
echo "      adb shell screencap -p /sdcard/settings.png"
echo "      adb pull /sdcard/settings.png docs/screenshots/"
echo ""
echo "   e) WIDGET (widget.png):"
echo "      - Torna alla home Android"
echo "      - Tieni premuto → Widget → StepsTracker"
echo "      - Posiziona il widget e cattura"
echo "      adb shell screencap -p /sdcard/widget.png"
echo "      adb pull /sdcard/widget.png docs/screenshots/"
echo ""
echo "   f) LOGIN (login.png):"
echo "      - Logout dall'app"
echo "      - Cattura schermata login"
echo "      adb shell screencap -p /sdcard/login.png"
echo "      adb pull /sdcard/login.png docs/screenshots/"
echo ""
echo "   g) REGISTRAZIONE (registration.png):"
echo "      - Dalla schermata login → Registrati"
echo "      - Compila form (non inviare)"
echo "      adb shell screencap -p /sdcard/registration.png"
echo "      adb pull /sdcard/registration.png docs/screenshots/"
echo ""
echo "5️⃣  OTTIMIZZA LE IMMAGINI (opzionale):"
echo "   for img in docs/screenshots/*.png; do"
echo "     convert \"\$img\" -resize 400x -quality 85 \"\$img\""
echo "   done"
echo ""
echo "================================"
echo ""
echo "🚀 COMANDI RAPIDI DA COPIARE:"
echo ""
echo "# Installa app"
echo "adb install -r $APK_PATH"
echo ""
echo "# Cattura tutti gli screenshot"
echo "mkdir -p docs/screenshots"
echo "adb shell screencap -p /sdcard/home.png && adb pull /sdcard/home.png docs/screenshots/"
echo "adb shell screencap -p /sdcard/statistics.png && adb pull /sdcard/statistics.png docs/screenshots/"
echo "adb shell screencap -p /sdcard/profile.png && adb pull /sdcard/profile.png docs/screenshots/"
echo "adb shell screencap -p /sdcard/settings.png && adb pull /sdcard/settings.png docs/screenshots/"
echo "adb shell screencap -p /sdcard/widget.png && adb pull /sdcard/widget.png docs/screenshots/"
echo "adb shell screencap -p /sdcard/login.png && adb pull /sdcard/login.png docs/screenshots/"
echo "adb shell screencap -p /sdcard/registration.png && adb pull /sdcard/registration.png docs/screenshots/"
echo ""